---
title: "Extreme Temperature Impact"
output: html_document
date: "2024-09-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(lattice)
library(ggplot2)
library(ggcorrplot)
library(colorspace)
library(corrplot)
library(ggstatsplot)
library(ggpubr)
library(sf)
library(spdep)
library(terra)
library(dlnm)
library(glmmTMB)
library(metafor)
library(meta)
library(mgcv)
library(splines)
library(ggdendro)
```

```{r}
full_dataset <- read.csv("../Data/Japan Data.csv")
full_dataset <- full_dataset %>% as.data.frame()
```

```{r}
population_data <- read_excel("../Data/Japan Population.xlsx",sheet=1)
colnames(population_data) <- c("NAME_1","Population","Year")
```

```{r}
full_dataset <- merge(full_dataset, population_data, by=c("NAME_1","Year"),all.x=TRUE) 
```

```{r}
geo_location <- read.csv("../Data/Japan LonLat.csv")
colnames(geo_location)[1] <- "NAME_1"
Japan.shapefile <- st_read('../Data/Japan_shp/JPN_adm1.shp')
Japan.shapefile <- sp::merge(Japan.shapefile,geo_location,by="NAME_1",duplicateGeoms = TRUE) %>% st_as_sf()
```

```{r}
nb_rook <- poly2nb(Japan.shapefile,queen = FALSE,row.names = Japan.shapefile$NAME_1) 
coords <-  st_coordinates(Japan.shapefile)
listw <- nb2listw(nb_rook,zero.policy = TRUE)
```

```{r}
matrix_list <- listw2mat(w_mat_d_p2)
colnames(matrix_list) <- Japan.shapefile$NAME_1
rownames(matrix_list) <- colnames(matrix_list)
matrix_list %>% as.data.frame()
```

```{r}
prefecture_list <- unique(full_dataset$NAME_1)
prefecture_list
```
## Cold Spells

### Crude Association (no offset, no covariates)

```{r}
for (i in 1:47){
  region_data <- full_dataset[full_dataset$NAME_1==prefecture_list[i],]
  region_data$Year <- as.numeric(region_data$Year)
  region_data$Week <- as.numeric(region_data$week)
  region_data$Case <- region_data$Cases
  region_data$Pop <- region_data$Population
  
  cb.p5_2d <- crossbasis(region_data$p5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p5_3d <- crossbasis(region_data$p5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_2d <- crossbasis(region_data$p7.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_3d <- crossbasis(region_data$p7.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_4d <- crossbasis(region_data$p7.5_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_2d <- crossbasis(region_data$p10_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_3d <- crossbasis(region_data$p10_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_4d <- crossbasis(region_data$p10_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_5d <- crossbasis(region_data$p10_5d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))

  crude_p5_2d_model <- gam(Case~cb.p5_2d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  crude_p5_3d_model <- gam(Case~cb.p5_3d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  crude_p7.5_2d_model <- gam(Case~cb.p7.5_2d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  crude_p7.5_3d_model <- gam(Case~cb.p7.5_3d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  crude_p7.5_4d_model <- gam(Case~cb.p7.5_4d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  crude_p10_2d_model <- gam(Case~cb.p10_2d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  crude_p10_3d_model <- gam(Case~cb.p10_3d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  crude_p10_4d_model <- gam(Case~cb.p10_4d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  crude_p10_5d_model <- gam(Case~cb.p10_5d,family=quasipoisson(),data=region_data,method='REML',select=TRUE)

  p5_2d.crude <- crosspred(cb.p5_2d,crude_p5_2d_model,cen=0,cumul=TRUE,by=1)
  p5_3d.crude <- crosspred(cb.p5_3d,crude_p5_3d_model,cen=0,cumul=TRUE,by=1)
  p7.5_2d.crude <- crosspred(cb.p7.5_2d,crude_p7.5_2d_model,cen=0,cumul=TRUE,by=1)
  p7.5_3d.crude <- crosspred(cb.p7.5_3d,crude_p7.5_3d_model,cen=0,cumul=TRUE,by=1)
  p7.5_4d.crude <- crosspred(cb.p7.5_4d,crude_p7.5_4d_model,cen=0,cumul=TRUE,by=1)
  p10_2d.crude <- crosspred(cb.p10_2d,crude_p10_2d_model,cen=0,cumul=TRUE,by=1)
  p10_3d.crude <- crosspred(cb.p10_3d,crude_p10_3d_model,cen=0,cumul=TRUE,by=1)
  p10_4d.crude <- crosspred(cb.p10_4d,crude_p10_4d_model,cen=0,cumul=TRUE,by=1)
  p10_5d.crude <- crosspred(cb.p10_5d,crude_p10_5d_model,cen=0,cumul=TRUE,by=1)
}
```

### Adjust for Population

```{r}
for (i in 1:47){
  region_data <- full_dataset[full_dataset$NAME_1==prefecture_list[i],]
  region_data$Year <- as.numeric(region_data$Year)
  region_data$Week <- as.numeric(region_data$week)
  region_data$Case <- region_data$Cases
  region_data$Pop <- region_data$Population
  
  cb.p5_2d <- crossbasis(region_data$p5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p5_3d <- crossbasis(region_data$p5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_2d <- crossbasis(region_data$p7.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_3d <- crossbasis(region_data$p7.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_4d <- crossbasis(region_data$p7.5_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_2d <- crossbasis(region_data$p10_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_3d <- crossbasis(region_data$p10_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_4d <- crossbasis(region_data$p10_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_5d <- crossbasis(region_data$p10_5d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))

  adjusted_p5_2d_model <- gam(Case~cb.p5_2d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  adjusted_p5_3d_model <- gam(Case~cb.p5_3d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  adjusted_p7.5_2d_model <- gam(Case~cb.p7.5_2d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  adjusted_p7.5_3d_model <- gam(Case~cb.p7.5_3d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  adjusted_p7.5_4d_model <- gam(Case~cb.p7.5_4d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  adjusted_p10_2d_model <- gam(Case~cb.p10_2d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  adjusted_p10_3d_model <- gam(Case~cb.p10_3d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  adjusted_p10_4d_model <- gam(Case~cb.p10_4d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  adjusted_p10_5d_model <- gam(Case~cb.p10_5d,offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  
  p5_2d.adjusted <- crosspred(cb.p5_2d,adjusted_p5_2d_model,cen=0,cumul=TRUE,by=1)
  p5_3d.adjusted <- crosspred(cb.p5_3d,adjusted_p5_3d_model,cen=0,cumul=TRUE,by=1)
  p7.5_2d.adjusted <- crosspred(cb.p7.5_2d,adjusted_p7.5_2d_model,cen=0,cumul=TRUE,by=1)
  p7.5_3d.adjusted <- crosspred(cb.p7.5_3d,adjusted_p7.5_3d_model,cen=0,cumul=TRUE,by=1)
  p7.5_4d.adjusted <- crosspred(cb.p7.5_4d,adjusted_p7.5_4d_model,cen=0,cumul=TRUE,by=1)
  p10_2d.adjusted <- crosspred(cb.p10_2d,adjusted_p10_2d_model,cen=0,cumul=TRUE,by=1)
  p10_3d.adjusted <- crosspred(cb.p10_3d,adjusted_p10_3d_model,cen=0,cumul=TRUE,by=1)
  p10_4d.adjusted <- crosspred(cb.p10_4d,adjusted_p10_4d_model,cen=0,cumul=TRUE,by=1)
  p10_5d.adjusted <- crosspred(cb.p10_5d,adjusted_p10_5d_model,cen=0,cumul=TRUE,by=1)
}
```

### Adjust for population and covariates

```{r}
for (i in 1:47){
  region_data <- full_dataset[full_dataset$NAME_1==prefecture_list[i],]
  region_data$Year <- as.numeric(region_data$Year)
  region_data$Week <- as.numeric(region_data$week)
  region_data$Case <- region_data$Cases
  region_data$Pop <- region_data$Population
  
  cb.p5_2d <- crossbasis(region_data$p5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p5_3d <- crossbasis(region_data$p5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_2d <- crossbasis(region_data$p7.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_3d <- crossbasis(region_data$p7.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_4d <- crossbasis(region_data$p7.5_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_2d <- crossbasis(region_data$p10_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_3d <- crossbasis(region_data$p10_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_4d <- crossbasis(region_data$p10_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_5d <- crossbasis(region_data$p10_5d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  uni_p5_2d_model <- gam(Case~cb.p5_2d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                         offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  uni_p5_3d_model <- gam(Case~cb.p5_3d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                         offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  uni_p7.5_2d_model <- gam(Case~cb.p7.5_2d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                         offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  uni_p7.5_3d_model <- gam(Case~cb.p7.5_3d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                           offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  uni_p7.5_4d_model <- gam(Case~cb.p7.5_4d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                           offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  uni_p10_2d_model <- gam(Case~cb.p10_2d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                          offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  uni_p10_3d_model <- gam(Case~cb.p10_3d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                          offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  uni_p10_4d_model <- gam(Case~cb.p10_4d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                          offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  uni_p10_5d_model <- gam(Case~cb.p10_5d+ns(TAVG,df=3)+ns(relative.humidity,df=3)+ns(PRCP,df=3)+ns(wind.speed,df=3),
                          offset=log(Pop),family=quasipoisson(),data=region_data,method='REML',select=TRUE)
  
  p5_2d.uni <- crosspred(cb.p5_2d,uni_p5_2d_model,cen=0,cumul=TRUE,by=1)
  p5_3d.uni <- crosspred(cb.p5_3d,uni_p5_3d_model,cen=0,cumul=TRUE,by=1)
  p7.5_2d.uni <- crosspred(cb.p7.5_2d,uni_p7.5_2d_model,cen=0,cumul=TRUE,by=1)
  p7.5_3d.uni <- crosspred(cb.p7.5_3d,uni_p7.5_3d_model,cen=0,cumul=TRUE,by=1)
  p7.5_4d.uni <- crosspred(cb.p7.5_4d,uni_p7.5_4d_model,cen=0,cumul=TRUE,by=1)
  p10_2d.uni <- crosspred(cb.p10_2d,uni_p10_2d_model,cen=0,cumul=TRUE,by=1)
  p10_3d.uni <- crosspred(cb.p10_3d,uni_p10_3d_model,cen=0,cumul=TRUE,by=1)
  p10_4d.uni <- crosspred(cb.p10_4d,uni_p10_4d_model,cen=0,cumul=TRUE,by=1)
  p10_5d.uni <- crosspred(cb.p10_5d,uni_p10_5d_model,cen=0,cumul=TRUE,by=1)
}
```
  
### Univariate spatiotemporal model (main model)

```{r}
for (i in 1:47){
  region_data <- full_dataset[full_dataset$NAME_1==prefecture_list[i],]
  neighbours_id <- which(colnames(matrix_list)==prefecture_list[i])
  neighbours_weight <- matrix_list[,neighbours_id]
  neighbours_weight <- neighbours_weight[neighbours_weight>0]
  neighbour_data <- matrix(NA,ncol=length(neighbours_weight),nrow=nrow(region_data))
  if (length(neighbours_weight)>=1){
    for (j in 1:length(neighbours_weight)){
      neighbour_data[,j] <- full_dataset[full_dataset$NAME_1==names(neighbours_weight)[j],"Cases"]*neighbours_weight[j]
    }
    colnames(neighbour_data) <- paste0("neighbour",seq(1:length(neighbours_weight)))
    region_data <- cbind(region_data,neighbour_data)
  }
  else{
    region_data <- region_data
  }
  region_data2 <- region_data
  colnames(region_data2) <- colnames(region_data)
  region_data2$Year <- as.numeric(region_data2$Year)
  region_data2$Week <- as.numeric(region_data2$week)
  region_data2$Cases <- region_data2$Cases
  
  cb.p5_2d <- crossbasis(region_data$p5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p5_3d <- crossbasis(region_data$p5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_2d <- crossbasis(region_data$p7.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_3d <- crossbasis(region_data$p7.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p7.5_4d <- crossbasis(region_data$p7.5_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_2d <- crossbasis(region_data$p10_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_3d <- crossbasis(region_data$p10_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_4d <- crossbasis(region_data$p10_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p10_5d <- crossbasis(region_data$p10_5d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  if(length(neighbours_weight)>=1){
    
    neighbour_list <- paste0("ns(neighbour",seq(1:length(neighbours_weight)),")")
    neighbour_list <- paste(neighbour_list, collapse = " + ")

    uni_st_p5_2d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                               "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p5_2d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p5_3d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                               "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p5_3d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
   
    uni_st_p7.5_2d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                 "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p7.5_2d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p7.5_3d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                 "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p7.5_3d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p7.5_4d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                 "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p7.5_4d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)

    uni_st_p10_2d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p10_2d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p10_3d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p10_3d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p10_4d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p10_4d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p10_5d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p10_5d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    }
  else{
    uni_st_p5_2d_model <- gam(Cases~cb.p5_2d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                              offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p5_3d_model <- gam(Cases~cb.p5_3d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                              offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p7.5_2d_model <- gam(Cases~cb.p7.5_2d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p7.5_3d_model <- gam(Cases~cb.p7.5_3d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p7.5_4d_model <- gam(Cases~cb.p7.5_4d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p10_2d_model <- gam(Cases~cb.p10_2d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p10_3d_model <- gam(Cases~cb.p10_3d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p10_4d_model <- gam(Cases~cb.p10_4d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p10_5d_model <- gam(Cases~cb.p10_5d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  }
  p5_2d.uni.st <- crosspred(cb.p5_2d,uni_st_p5_2d_model,cen=1,cumul=TRUE,by=1)
  p5_3d.uni.st <- crosspred(cb.p5_3d,uni_st_p5_3d_model,cen=1,cumul=TRUE,by=1)
  
  p75_2d.uni.st <- crosspred(cb.p7.5_2d,uni_st_p7.5_2d_model,cen=1,cumul=TRUE,by=1)
  p75_3d.uni.st <- crosspred(cb.p7.5_3d,uni_st_p7.5_3d_model,cen=1,cumul=TRUE,by=1)
  p75_4d.uni.st <- crosspred(cb.p7.5_4d,uni_st_p7.5_4d_model,cen=1,cumul=TRUE,by=1)
  
  p10_2d.uni.st <- crosspred(cb.p10_2d,uni_st_p10_2d_model,cen=1,cumul=TRUE,by=1)
  p10_3d.uni.st <- crosspred(cb.p10_3d,uni_st_p10_3d_model,cen=1,cumul=TRUE,by=1)
  p10_4d.uni.st <- crosspred(cb.p10_4d,uni_st_p10_4d_model,cen=1,cumul=TRUE,by=1)
  p10_5d.uni.st <- crosspred(cb.p10_5d,uni_st_p10_5d_model,cen=1,cumul=TRUE,by=1)
}
```

## Heat Waves

### Crude Association (no offset, no covariates)

```{r}
for (i in 1:47){
  region_data <- full_dataset[full_dataset$NAME_1==prefecture_list[i],]
  region_data2 <- region_data
  colnames(region_data2) <- colnames(region_data)
  region_data2$Year <- as.numeric(region_data2$Year)
  region_data2$Week <- as.numeric(region_data2$week)
  region_data2$Cases <- region_data2$Cases
  
  cb.p97.5_2d <- crossbasis(region_data2$p97.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p97.5_3d <- crossbasis(region_data2$p97.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p95_2d <- crossbasis(region_data2$p95_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p95_3d <- crossbasis(region_data2$p95_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p92.5_2d <- crossbasis(region_data2$p92.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p92.5_3d <- crossbasis(region_data2$p92.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p92.5_4d <- crossbasis(region_data2$p92.5_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p90_2d <- crossbasis(region_data2$p90_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_3d <- crossbasis(region_data2$p90_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_4d <- crossbasis(region_data2$p90_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_5d <- crossbasis(region_data2$p90_5d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  crude_p97.5_2d_model <- gam(Cases~cb.p97.5_2d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  crude_p97.5_3d_model <- gam(Cases~cb.p97.5_3d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    
  crude_p95_2d_model <- gam(Cases~cb.p95_2d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  crude_p95_3d_model <- gam(Cases~cb.p95_3d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  
  crude_p92.5_2d_model <- gam(Cases~cb.p92.5_2d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  crude_p92.5_3d_model <- gam(Cases~cb.p92.5_3d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  crude_p92.5_4d_model <- gam(Cases~cb.p92.5_4d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    
  crude_p90_2d_model <- gam(Cases~cb.p90_2d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  crude_p90_3d_model <- gam(Cases~cb.p90_3d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  crude_p90_4d_model <- gam(Cases~cb.p90_4d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  crude_p90_5d_model <- gam(Cases~cb.p90_5d,family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
  
  p975_2d.crude <- crosspred(cb.p97.5_2d,crude_p97.5_2d_model,cen=1,cumul=TRUE,by=1)
  p975_3d.crude <- crosspred(cb.p97.5_3d,crude_p97.5_3d_model,cen=1,cumul=TRUE,by=1)

  p95_2d.crude <- crosspred(cb.p95_2d,crude_p95_2d_model,cen=1,cumul=TRUE,by=1)
  p95_3d.crude <- crosspred(cb.p95_3d,crude_p95_3d_model,cen=1,cumul=TRUE,by=1)
  p95_4d.crude <- crosspred(cb.p95_4d,crude_p95_4d_model,cen=1,cumul=TRUE,by=1)
  
  p925_2d.crude <- crosspred(cb.p92.5_2d,crude_p92.5_2d_model,cen=1,cumul=TRUE,by=1)
  p925_3d.crude <- crosspred(cb.p92.5_3d,crude_p92.5_3d_model,cen=1,cumul=TRUE,by=1)
  p925_4d.crude <- crosspred(cb.p92.5_4d,crude_p92.5_4d_model,cen=1,cumul=TRUE,by=1)
  
  p90_2d.crude <- crosspred(cb.p90_2d,crude_p90_2d_model,cen=1,cumul=TRUE,by=1)
  p90_3d.crude <- crosspred(cb.p90_3d,crude_p90_3d_model,cen=1,cumul=TRUE,by=1)
  p90_4d.crude <- crosspred(cb.p90_4d,crude_p90_4d_model,cen=1,cumul=TRUE,by=1)
  p90_5d.crude <- crosspred(cb.p90_5d,crude_p90_5d_model,cen=1,cumul=TRUE,by=1)
}
```

### Adjust for population 

```{r}
for (i in 1:47){
  region_data <- full_dataset[full_dataset$NAME_1==prefecture_list[i],]
  region_data2 <- region_data
  colnames(region_data2) <- colnames(region_data)
  region_data2$Year <- as.numeric(region_data2$Year)
  region_data2$Week <- as.numeric(region_data2$week)
  region_data2$Cases <- region_data2$Cases
  
  cb.p97.5_2d <- crossbasis(region_data2$p97.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p97.5_3d <- crossbasis(region_data2$p97.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p95_2d <- crossbasis(region_data2$p95_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p95_3d <- crossbasis(region_data2$p95_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p92.5_2d <- crossbasis(region_data2$p92.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p92.5_3d <- crossbasis(region_data2$p92.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p92.5_4d <- crossbasis(region_data2$p92.5_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p90_2d <- crossbasis(region_data2$p90_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_3d <- crossbasis(region_data2$p90_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_4d <- crossbasis(region_data2$p90_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_5d <- crossbasis(region_data2$p90_5d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  adjust_p97.5_2d_model <- gam(Cases~cb.p97.5_2d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  adjust_p97.5_3d_model <- gam(Cases~cb.p97.5_3d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
    
  adjust_p95_2d_model <- gam(Cases~cb.p95_2d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  adjust_p95_3d_model <- gam(Cases~cb.p95_3d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  adjust_p95_4d_model <- gam(Cases~cb.p95_4d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
    
  adjust_p92.5_2d_model <- gam(Cases~cb.p92.5_2d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  adjust_p92.5_3d_model <- gam(Cases~cb.p92.5_3d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  adjust_p92.5_4d_model <- gam(Cases~cb.p92.5_4d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
    
  adjust_p90_2d_model <- gam(Cases~cb.p90_2d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  adjust_p90_3d_model <- gam(Cases~cb.p90_3d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  adjust_p90_4d_model <- gam(Cases~cb.p90_4d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  adjust_p90_5d_model <- gam(Cases~cb.p90_5d,family=quasipoisson(),offset=log(Population),data=region_data2,method='REML',select=TRUE)
  
  p975_2d.adjust <- crosspred(cb.p97.5_2d,adjust_p97.5_2d_model,cen=1,cumul=TRUE,by=1)
  p975_3d.adjust <- crosspred(cb.p97.5_3d,adjust_p97.5_3d_model,cen=1,cumul=TRUE,by=1)

  p95_2d.adjust <- crosspred(cb.p95_2d,adjust_p95_2d_model,cen=1,cumul=TRUE,by=1)
  p95_3d.adjust <- crosspred(cb.p95_3d,adjust_p95_3d_model,cen=1,cumul=TRUE,by=1)
  
  p925_2d.adjust <- crosspred(cb.p92.5_2d,adjust_p92.5_2d_model,cen=1,cumul=TRUE,by=1)
  p925_3d.adjust <- crosspred(cb.p92.5_3d,adjust_p92.5_3d_model,cen=1,cumul=TRUE,by=1)
  p925_4d.adjust <- crosspred(cb.p92.5_4d,adjust_p92.5_4d_model,cen=1,cumul=TRUE,by=1)
  
  p90_2d.adjust <- crosspred(cb.p90_2d,adjust_p90_2d_model,cen=1,cumul=TRUE,by=1)
  p90_3d.adjust <- crosspred(cb.p90_3d,adjust_p90_3d_model,cen=1,cumul=TRUE,by=1)
  p90_4d.adjust <- crosspred(cb.p90_4d,adjust_p90_4d_model,cen=1,cumul=TRUE,by=1)
  p90_5d.adjust <- crosspred(cb.p90_5d,adjust_p90_5d_model,cen=1,cumul=TRUE,by=1)
}
```

### Adjust for population and covariates

```{r}
for (i in 1:47){
  region_data <- full_dataset[full_dataset$NAME_1==prefecture_list[i],]
  region_data2 <- region_data
  colnames(region_data2) <- colnames(region_data)
  region_data2$Year <- as.numeric(region_data2$Year)
  region_data2$Week <- as.numeric(region_data2$week)
  region_data2$Cases <- region_data2$Cases
  
  cb.p97.5_2d <- crossbasis(region_data2$p97.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p97.5_3d <- crossbasis(region_data2$p97.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p95_2d <- crossbasis(region_data2$p95_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p95_3d <- crossbasis(region_data2$p95_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p92.5_2d <- crossbasis(region_data2$p92.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p92.5_3d <- crossbasis(region_data2$p92.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p92.5_4d <- crossbasis(region_data2$p92.5_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p90_2d <- crossbasis(region_data2$p90_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_3d <- crossbasis(region_data2$p90_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_4d <- crossbasis(region_data2$p90_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_5d <- crossbasis(region_data2$p90_5d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  uni_p97.5_2d_model <- gam(Cases~cb.p97.5_2d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  uni_p97.5_3d_model <- gam(Cases~cb.p97.5_3d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    
  uni_p95_2d_model <- gam(Cases~cb.p95_2d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  uni_p95_3d_model <- gam(Cases~cb.p95_3d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    
  uni_p92.5_2d_model <- gam(Cases~cb.p92.5_2d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  uni_p92.5_3d_model <- gam(Cases~cb.p92.5_3d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  uni_p92.5_4d_model <- gam(Cases~cb.p92.5_4d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    
  uni_p90_2d_model <- gam(Cases~cb.p90_2d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  uni_p90_3d_model <- gam(Cases~cb.p90_3d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  uni_p90_4d_model <- gam(Cases~cb.p90_4d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  uni_p90_5d_model <- gam(Cases~cb.p90_5d+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  
  p975_2d.uni <- crosspred(cb.p97.5_2d,uni_p97.5_2d_model,cen=1,cumul=TRUE,by=1)
  p975_3d.uni <- crosspred(cb.p97.5_3d,uni_p97.5_3d_model,cen=1,cumul=TRUE,by=1)

  p95_2d.uni <- crosspred(cb.p95_2d,uni_p95_2d_model,cen=1,cumul=TRUE,by=1)
  p95_3d.uni <- crosspred(cb.p95_3d,uni_p95_3d_model,cen=1,cumul=TRUE,by=1)
  
  p925_2d.uni <- crosspred(cb.p92.5_2d,uni_p92.5_2d_model,cen=1,cumul=TRUE,by=1)
  p925_3d.uni <- crosspred(cb.p92.5_3d,uni_p92.5_3d_model,cen=1,cumul=TRUE,by=1)
  p925_4d.uni <- crosspred(cb.p92.5_4d,uni_p92.5_4d_model,cen=1,cumul=TRUE,by=1)
  
  p90_2d.uni <- crosspred(cb.p90_2d,uni_p90_2d_model,cen=1,cumul=TRUE,by=1)
  p90_3d.uni <- crosspred(cb.p90_3d,uni_p90_3d_model,cen=1,cumul=TRUE,by=1)
  p90_4d.uni <- crosspred(cb.p90_4d,uni_p90_4d_model,cen=1,cumul=TRUE,by=1)
  p90_5d.uni <- crosspred(cb.p90_5d,uni_p90_5d_model,cen=1,cumul=TRUE,by=1)
}
```

### Univariate spatiotemporal model (main model)

```{r}
for (i in 1:47){
  region_data <- full_dataset[full_dataset$NAME_1==prefecture_list[i],]
  neighbours_id <- which(colnames(matrix_list)==prefecture_list[i])
  neighbours_weight <- matrix_list[,neighbours_id]
  neighbours_weight <- neighbours_weight[neighbours_weight>0]
  neighbour_data <- matrix(NA,ncol=length(neighbours_weight),nrow=nrow(region_data))
  if (length(neighbours_weight)>=1){
    for (j in 1:length(neighbours_weight)){
      neighbour_data[,j] <- full_dataset[full_dataset$NAME_1==names(neighbours_weight)[j],"Cases"]*neighbours_weight[j]
    }
    colnames(neighbour_data) <- paste0("neighbour",seq(1:length(neighbours_weight)))
    region_data <- cbind(region_data,neighbour_data)
  }
  else{
    region_data <- region_data
  }
  region_data2 <- region_data
  colnames(region_data2) <- colnames(region_data)
  region_data2$Year <- as.numeric(region_data2$Year)
  region_data2$Week <- as.numeric(region_data2$week)
  region_data2$Cases <- region_data2$Cases
  
  cb.p97.5_2d <- crossbasis(region_data2$p97.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p97.5_3d <- crossbasis(region_data2$p97.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p95_2d <- crossbasis(region_data2$p95_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p95_3d <- crossbasis(region_data2$p95_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p92.5_2d <- crossbasis(region_data2$p92.5_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p92.5_3d <- crossbasis(region_data2$p92.5_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p92.5_4d <- crossbasis(region_data2$p92.5_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  cb.p90_2d <- crossbasis(region_data2$p90_2d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_3d <- crossbasis(region_data2$p90_3d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_4d <- crossbasis(region_data2$p90_4d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  cb.p90_5d <- crossbasis(region_data2$p90_5d_continuous,lag=3,argvar=list(fun="lin"),arglag=list(fun="ns",df=2))
  
  if(length(neighbours_weight)>=1){
    
    neighbour_list <- paste0("ns(neighbour",seq(1:length(neighbours_weight)),")")
    neighbour_list <- paste(neighbour_list, collapse = " + ")
  
    uni_st_p97.5_2d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                  "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p97.5_2d+ns(wind.speed,df=3)")),
                                offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p97.5_3d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                  "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p97.5_3d+ns(wind.speed,df=3)")),
                                offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    
    uni_st_p95_2d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p95_2d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p95_3d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p95_3d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    
    uni_st_p92.5_2d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                  "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p92.5_2d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p92.5_3d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                  "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p92.5_3d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p92.5_4d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                  "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p92.5_4d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    
    uni_st_p90_2d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p90_2d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p90_3d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p90_3d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p90_4d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p90_4d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    uni_st_p90_5d_model <- gam(as.formula(paste("Cases ~",neighbour_list,
                                                "+ s(Week) + ns(TAVG,df=3) + ns(PRCP,df=3) + ns(relative.humidity,df=3) + cb.p90_5d+ns(wind.speed,df=3)")),
                               offset=log(Population),family=quasipoisson(),data=region_data2,method='REML',select=TRUE)
    }
  else{
    uni_st_p97.5_2d_model <- gam(Cases~cb.p97.5_2d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p97.5_3d_model <- gam(Cases~cb.p97.5_3d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    
    uni_st_p95_2d_model <- gam(Cases~cb.p95_2d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p95_3d_model <- gam(Cases~cb.p95_3d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)

    uni_st_p92.5_2d_model <- gam(Cases~cb.p92.5_2d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p92.5_3d_model <- gam(Cases~cb.p92.5_3d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p92.5_4d_model <- gam(Cases~cb.p92.5_4d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    
    uni_st_p90_2d_model <- gam(Cases~cb.p90_2d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p90_3d_model <- gam(Cases~cb.p90_3d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p90_4d_model <- gam(Cases~cb.p90_4d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
    uni_st_p90_5d_model <- gam(Cases~cb.p90_5d+s(Week)+ns(TAVG,df=3)+ns(PRCP,df=3)+ns(relative.humidity,df=3)+ns(wind.speed,df=3),family=quasipoisson(),
                                offset=log(Population),data=region_data2,method='REML',select=TRUE)
  }
  
  p975_2d.uni.st <- crosspred(cb.p97.5_2d,uni_st_p97.5_2d_model,cen=1,cumul=TRUE,by=1)
  p975_3d.uni.st <- crosspred(cb.p97.5_3d,uni_st_p97.5_3d_model,cen=1,cumul=TRUE,by=1)

  p95_2d.uni.st <- crosspred(cb.p95_2d,uni_st_p95_2d_model,cen=1,cumul=TRUE,by=1)
  p95_3d.uni.st <- crosspred(cb.p95_3d,uni_st_p95_3d_model,cen=1,cumul=TRUE,by=1)
  
  p925_2d.uni.st <- crosspred(cb.p92.5_2d,uni_st_p92.5_2d_model,cen=1,cumul=TRUE,by=1)
  p925_3d.uni.st <- crosspred(cb.p92.5_3d,uni_st_p92.5_3d_model,cen=1,cumul=TRUE,by=1)
  p925_4d.uni.st <- crosspred(cb.p92.5_4d,uni_st_p92.5_4d_model,cen=1,cumul=TRUE,by=1)
  
  p90_2d.uni.st <- crosspred(cb.p90_2d,uni_st_p90_2d_model,cen=1,cumul=TRUE,by=1)
  p90_3d.uni.st <- crosspred(cb.p90_3d,uni_st_p90_3d_model,cen=1,cumul=TRUE,by=1)
  p90_4d.uni.st <- crosspred(cb.p90_4d,uni_st_p90_4d_model,cen=1,cumul=TRUE,by=1)
  p90_5d.uni.st <- crosspred(cb.p90_5d,uni_st_p90_5d_model,cen=1,cumul=TRUE,by=1)
}
```
